name: python-labs
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - keras
  - python=3.12.2
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
